export const bookCategory = [
    'Science',
    'Philosophy',
    'Art',
    'Business',
    'Self-Help',
    'Development',
    'Motivational',
    'Health',
    'Families & Relationships',
    'Guide / How-to',
    'Maths',
    'History',
    'Encyclopedia',
    'Autobiography',
    'Action and Adventure',
    'Fantasy',
    'Science Fiction',
    'Economics',
    'Non-fiction',
    'Others'
]